### ISSUE TITLE
Custom camera and microphone permission support

### ISSUE THREAD

**Issue by dhanrajsinh24** [natml-hub/NatCorder-ARFoundation-Sample#1]
Hi, My client wants to buy Natcorder asset from Asset store but we want to confirm first if we can force Camera and Microphone permission at app start (basically whenever we want) and not when the recording starts. Is that possible?

Thanks,
Dan.

**Comment by olokobayusuf** [comment]
Hey @dhanrajsinh24 , NatCorder doesn't handle any permissions. Instead, you can use the method that Unity provides, [Application.RequestUserAuthorization](https://docs.unity3d.com/ScriptReference/Application.RequestUserAuthorization.html).
