### ISSUE TITLE
Does Not find cameraInput.frameInput and (GLESRenderTextureInput & MTLRenderTextureInput)

### ISSUE THREAD

**Issue by Rutherfordum** [natml-hub/NatCorder-ARFoundation-Sample#2]
Hi!
I have does not find cameraInput.frameInput and (GLESRenderTextureInput & MTLRenderTextureInput)
![image](https://user-images.githubusercontent.com/34240232/129458710-597e9e9b-6c30-4e2d-988c-c9a27de05da8.png)

And i'm do this 
![image](https://user-images.githubusercontent.com/34240232/129458732-d127f0d2-db8d-468d-9c20-7c509a85289b.png)

The errors disappeared, but it did not help me, the application is building but the video does not record

i'm used:
Unity 2019.4.20.f1
ARFoundation 4.1
NatCorder 1.8.1

**Comment by olokobayusuf** [comment]
Hey there, the second picture you shared is the correct way to do it after the NatCorder 1.8.1 update. Can you explain more about the video not recording? Can you share the logs from the device?

**Comment by Rutherfordum** [comment]
> Hey there, the second picture you shared is the correct way to do it after the NatCorder 1.8.1 update. Can you explain more about the video not recording? Can you share the logs from the device?

Releasing render texture that is set to be RenderTexture.active!
08-16 06:55:11.677 30311   383 W Unity   : NatSuite.Rendering.ReadbackDelegate:Invoke(NativeArray`1)
08-16 06:55:11.677 30311   383 W Unity   : System.Threading.ContextCallback:Invoke(Object)
08-16 06:55:11.677 30311   383 W Unity   : System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
08-16 06:55:11.677 30311   383 W Unity   : System.Runtime.CompilerServices.MoveNextRunner:Run()
08-16 06:55:11.677 30311   383 W Unity   : System.Action:Invoke()
08-16 06:55:11.677 30311   383 W Unity   : System.Threading.SendOrPostCallback:Invoke(Object)
08-16 06:55:11.677 30311   383 W Unity   : UnityEngine.UnitySynchronizationContext:Exec()
08-16 06:55:11.677 30311   383 W Unity   : UnityEngine.UnitySynchronizationContext:Exec()
08-16 06:55:11.677 30311   383 W Unity   :
08-16 06:55:11.677 30311   383 W Unity   : [ line 926]
08-16 06:55:11.677 30311   383 W Unity   : (Filename:  Line: 926)
08-16 06:55:11.677 30311   383 W Unity   :

**Comment by Rutherfordum** [comment]
> Hey there, the second picture you shared is the correct way to do it after the NatCorder 1.8.1 update. Can you explain more about the video not recording? Can you share the logs from the device?

08-16 06:55:03.229 30311   383 E Unity   : Unable to find _burst_generated
08-16 06:55:11.677 30311   383 W Unity   : Releasing render texture that is set to be RenderTexture.active!
08-16 06:55:11.677 30311   383 W Unity   : NatSuite.Rendering.ReadbackDelegate:Invoke(NativeArray`1)
08-16 06:55:11.677 30311   383 W Unity   : System.Threading.ContextCallback:Invoke(Object)
08-16 06:55:11.677 30311   383 W Unity   : System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
08-16 06:55:11.677 30311   383 W Unity   : System.Runtime.CompilerServices.MoveNextRunner:Run()
08-16 06:55:11.677 30311   383 W Unity   : System.Action:Invoke()
08-16 06:55:11.677 30311   383 W Unity   : System.Threading.SendOrPostCallback:Invoke(Object)
08-16 06:55:11.677 30311   383 W Unity   : UnityEngine.UnitySynchronizationContext:Exec()
08-16 06:55:11.677 30311   383 W Unity   : UnityEngine.UnitySynchronizationContext:Exec()
08-16 06:55:11.677 30311   383 W Unity   :
08-16 06:55:11.677 30311   383 W Unity   : [ line 926]
08-16 06:55:11.677 30311   383 W Unity   : (Filename:  Line: 926)
08-16 06:55:11.677 30311   383 W Unity   :

**Comment by olokobayusuf** [comment]
> > Hey there, the second picture you shared is the correct way to do it after the NatCorder 1.8.1 update. Can you explain more about the video not recording? Can you share the logs from the device?
> 
> 08-16 06:55:03.229 30311 383 E Unity : Unable to find _burst_generated
> 08-16 06:55:11.677 30311 383 W Unity : Releasing render texture that is set to be RenderTexture.active!
> 08-16 06:55:11.677 30311 383 W Unity : NatSuite.Rendering.ReadbackDelegate:Invoke(NativeArray`1)
> 08-16 06:55:11.677 30311 383 W Unity : System.Threading.ContextCallback:Invoke(Object)
> 08-16 06:55:11.677 30311 383 W Unity : System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
> 08-16 06:55:11.677 30311 383 W Unity : System.Runtime.CompilerServices.MoveNextRunner:Run()
> 08-16 06:55:11.677 30311 383 W Unity : System.Action:Invoke()
> 08-16 06:55:11.677 30311 383 W Unity : System.Threading.SendOrPostCallback:Invoke(Object)
> 08-16 06:55:11.677 30311 383 W Unity : UnityEngine.UnitySynchronizationContext:Exec()
> 08-16 06:55:11.677 30311 383 W Unity : UnityEngine.UnitySynchronizationContext:Exec()
> 08-16 06:55:11.677 30311 383 W Unity :
> 08-16 06:55:11.677 30311 383 W Unity : [ line 926]
> 08-16 06:55:11.677 30311 383 W Unity : (Filename: Line: 926)
> 08-16 06:55:11.677 30311 383 W Unity :

Earlier today I [pushed an update to NCPX](https://github.com/natsuite/NatCorder-Performance-Extensions). I recommend grabbing it and trying to see if this issue has been resolved.

EDIT: `MTLTextureInput` has been removed.

**Comment by gtk2k** [comment]
@olokobayusuf 
>Hey there, the second picture you shared is the correct way to do it after the NatCorder 1.8.1 update. 

Please also update the code in the repository.

**Comment by olokobayusuf** [comment]
9eb1740f12708668e2219e53516a1cd5f8e970a2
